### ISSUE TITLE
Please share mongo.env

### ISSUE THREAD

**Issue by varqasim** [LukeMwila/multi-container-nginx-react-node-mongo#1]
Hi. I have been having a hard time setting up mongodb with compose. I followed the files that you have provided in order to initialise the DB with a user and a database. When the express server tries to connect to the database it throws an error that the user (created in the `init-mongo.js` file is not found on the database that was chosen in the same file. Mind you I am specifying both variables `MONGO_INITDB_ROOT_USERNAME` and `MONGO_INITDB_ROOT_PASSWORD`. Even without them I am getting the same problem.

Curious on how you set this up using the .env file.

**Comment by LukeMwila** [comment]
Hi there, 

So you can create an env directory/folder at the root level of your project and create the following two files:
- backend.env
- mongo.env

The **backend.env** file
This file has the env variable for the node-js container with a value for the database connection string. Inside the backend folder, you'll find a db.js file in backend/src/config. This file contains a constant making use of this env variable for the database connection string.

Example:
// Add the following content to your backend.env file
TO_DO_DB=mongodb://username:password@mongo:27017/your-database-name

The **mongo.env** file
This file has the env variables for the mongo container with values used during the initialisation of your mongo database. 

Example:
// Add the following content to your mongo.env file
MONGO_INITDB_DATABASE=your-database-name
MONGO_INITDB_USERNAME=your-super-user
MONGO_INITDB_PASSWORD=super-user-password

I'll be updating the README.md file to include this information and setup instructions so that people don't run into similar issues.

**Comment by varqasim** [comment]
Thank you for the quick reply. So it turns out the first time I ran mongodb container without setting up the proper authentication. I had to delete the volume and when running it again it connected :) Was weird because I haven't specified any mounted volumes, but yet there was a persistent volume with the first configurations I ran mongodb with.
